version: '3'
services:
  db:
    image: store_x:8
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE='store'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD=''
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_HOST=''
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db
volumes:
  db: